name: Testcafe 
on: [push]

jobs:
  test:
    name: Run testcafe
    runs-on: macos-latest
    steps: 
      - name: Check repo
        uses: actions/checkout@v1
      - name: Run tests 
        uses: 
        with: 
            args: "chrome:headless src/api/**.spec.js"