name: Testcafe 
on: [push]

jobs:
  test:
    name: Run testcafe
    runs-on: windows-latest
    steps: 
      - name: Check repo
        uses: actions/checkout@v1
      - name: Run api tests 
        uses: DevExpress/testcafe-action@latest
        with: 
            args: "chrome:headless src/api/"